ebot:
  image: docker.stammgruppe.eu/ebot:4
  restart: always
  links:
    - "mysql:mysql"
  ports:
    - "12360:12360"
    - "12361:12361"
    - "12360:12360/udp"
    - "12361:12361/udp"
  volumes:
    - /opt/docker/ebot/logs:/ebot/logs
    - /opt/docker/ebot/demos:/ebot/demos
  environment:
    EXTERNAL_IP: 'xxx.xxx.xxx.xxx'
    BOT_PORT: '12360'
    MYSQL_HOST: 'mysql'
    MYSQL_PORT: '3306'
    MYSQL_DB: 'ebotv3'
    MYSQL_USER: 'ebotv3'
    MYSQL_PASS: 'ebotv3'
    SSL_ENABLED: 'false'
    SSL_CERTIFICATE_PATH: 'ssl/cert.pem'
    SSL_KEY_PATH: 'ssl/key.pem'
    MANAGE_PLAYER: '1'
    DELAY_BUSY_SERVER: '120'
    NB_MAX_MATCHS: '0'
    PAUSE_METHOD: 'nextRound'
    MAP: 'de_test1 de_test2 de_test3'
    COMMAND_STOP_DISABLED: 'false'
    RECORD_METHOD: 'matchstart'
    LO3_METHOD: 'restart'
    KO3_METHOD: 'restart'
    DEMO_DOWNLOAD: 'true'
    REMIND_RECORD: 'false'
    DAMAGE_REPORT: 'true'
    DELAY_READY: 'false'
    NODE_STARTUP_METHOD: 'node'
    TOORNAMENT_PLUGIN_KEY: ''
    USE_DELAY_END_RECORD: 'true'

ebotweb:
  image: docker.stammgruppe.eu/ebotweb:1
  restart: always
  links:
    - "mysql:mysql"
  ports:
    - "80:80"
  volumes:
    - /opt/docker/ebot/demos:/opt/ebot/demos
    - /opt/docker/ebot/logs:/opt/ebotlogs
  environment:
    EBOT_IP: 'xxx.xxx.xxx.xxx'
    EBOT_PORT: '12360'
    EBOT_ADMIN_USER: 'admin'
    EBOT_ADMIN_PASS: 'password'
    EBOT_ADMIN_MAIL: ''
    MYSQL_HOST: 'mysql'
    MYSQL_PORT: '3306'
    MYSQL_DB: 'ebotv3'
    MYSQL_USER: 'ebotv3'
    MYSQL_PASS: 'ebotv3'
    DEMO_DOWNLOAD: 'true'
    DEFAULT_MAX_ROUND: '15'
    DEFAULT_RULES: 'esl5on5'
    DEFAULT_OVERTIME_MAX_ROUND: '3'
    DEFAULT_OVERTIME_STARTMONEY: '16000'
    MODE: 'net'
    REFRESH_TIME: '30'
    TOORNAMENT_ID: ''
    TOORNAMENT_SECRET: ''
    TOORNAMENT_API_KEY: ''
    TOORNAMENT_PLUGIN_KEY: ''

mysql:
  image: mysql
  restart: always
  volumes:
    - /opt/docker/ebot/mysql:/var/lib/mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    - MYSQL_DATABASE=ebotv3
    - MYSQL_USER=ebotv3
    - MYSQL_PASSWORD=ebotv3
    - MYSQL_ROOT_PASSWORD=MyAwesomePassword
    - MYSQL_ROOT_HOST=%
  command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
